config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
   controllers: { sessions: 'users/sessions'}

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  get 'contact_us', to: 'contact_us#show'
  post 'contact_us/create', to: 'contact_us#create'
  get 'badges', to: 'badges#index'

  namespace :my do
    get 'badges', to: 'badge_issueds#index'
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end

end

app/models/admin.rb
class Admin < User

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answers_count, on: :create

  scope :correct, -> { where(correct: true) }


  private

  def answers_count
    message = "Количество ответов не должно превышать 4"
    errors.add(:answer_count, message) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_issueds, dependent: :destroy
  has_many :users, through: :badge_issueds

  validates :name, presence: true, uniqueness: true
  validates :img, presence: true
  validates :rule_type, presence: true
end

app/models/badge_issued.rb
class BadgeIssued < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true, uniqueness: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author , class_name: "User"
  has_many :questions, dependent: :destroy
  has_many :test_passages
  has_many :users, through: :test_passages

  validates :title, presence: true, uniqueness: {scope: :level}
  validates :level, numericality: {
    only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :averages, -> { where(level: 2..4) }
  scope :difficult, -> { where(level: 5..Float::INFINITY) }

  scope :by_category, -> (category_title) {
    joins(:category)
    .where(categories: { title: category_title }).order(title: :desc)
  }

  def self.titles_by_category(category_title)
    by_category(category_title).pluck(:title)
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :before_save_set_next_question

  def complete!
    self.current_question = nil
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def correct_percent
    (100.to_f/test.questions.count)*correct_questions
  end

  def questions_counter
    test.questions.where('id <= ?', current_question.id).count
  end

  def success?
    correct_percent > 84
  end

  def time_is_up?
    remaining_time < 0 if remaining_time
  end

  def remaining_time
    self.test.timer*60 - (Time.now - self.created_at).ceil if self.test.timer
  end

  private

  def before_save_set_next_question
    self.current_question = next_question
  end

  def next_question
    if current_question.nil?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.pluck(:id).sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: "Test", foreign_key: "author_id"
  has_many :gists
  has_many :badge_issueds
  has_many :badges, through: :badge_issueds

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true,
  format: { with: /.+@.+\..+/i }
  validates :password, presence: true
  validates :password, confirmation: true

  def passed_tests(level)
    self.tests.where("level = :level", level: level).distinct
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def admin?
    is_a?(Admin)
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :find_badges, only: :index
  before_action :find_badge, only: %i[show edit update destroy]

  def index
  end

  def new
    @badge = Badge.new
  end

  def show
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit(:name, :img, :rule_type, :param)
  end

  def find_badges
    @badges = Badge.all
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_sign_up_and_account_update_params, if: :devise_controller?
  before_action :set_locale

  def default_url_options
    { locale: (I18n.locale if I18n.locale != I18n.default_locale) }
  end

  protected

   def after_sign_in_path_for(resource)
     if resource.admin?
       admin_tests_path
     else
       super
     end

   end

   def configure_sign_up_and_account_update_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name])
   end

   def set_locale
     I18n.locale = I18n.locale_available?(params[:locale]) ? params[:locale] : I18n.default_locale
   end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController

  def show_form
  end

  def send_mail
    message = params[:body]
    user = current_user

    ContactUsMailer.send_mail(user, message).deliver_now
    redirect_to tests_path, notice: t('.success')
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def test_params
    params.require(:test).permit(:title, :level, :category_id)
  end

  def find_test
    @test = Test.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def curren_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

end

app/helpers/bagdes_helper.rb
module BagdesHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/badges/_badge.html.slim
tr
  td.align-middle = badge.name
  td.align-middle = image_tag badge.img
  td.align-middle = link_to 'Show', admin_badge_path(badge)
  td.align-middle = link_to 'Edit', edit_admin_badge_path(badge)
  td.align-middle = link_to 'Delete', admin_badge_path(badge), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/badges/_form.html.slim
.row.justify-content-center
  .col.col-md-4
    = form_with model: [:admin, @badge], local: true do |form|
      = render 'shared/errors', resourse: @badge

      .form-group
         = form.label :name
         = form.text_field :name, class:"form-control"
      .form-group
        = form.label :img
        = form.text_field :img, class:"form-control"
        small id="emailHelp" class="form-text text-muted" Вставте URL адрес изобразения.
      .form-group
        = form.label :rule_type
        = form.select(:rule_type, BadgeService::BADGES_RULE_TIPES)
        small id="emailHelp" class="form-text text-muted" Обязательно выберите тип награды.
      .form-group
        = form.label :param
        = form.text_field :param
        small id="emailHelp" class="form-text text-muted" Введите доп. параметр (например категорию или уровень).
      .btn.btn-primary
        = form.submit

= link_to t('.back'), admin_badges_path(@badge)

app/views/admin/badges/destroy.html.slim
h1 Bagdes#destroy
p Find me in app/views/bagdes/destroy.html.slim

app/views/admin/badges/edit.html.slim
h1 Edit badge

= render 'form'

app/views/admin/badges/index.html.slim
= link_to 'Создать новую награду', new_admin_badge_path
table.table.table-striped
  caption style='caption-side:top' Награды
  thead.thead-dark
    tr
      th = "Name"
      th = "Img"
      th colspan='3' = "Actions"
  tbody
    = render @badges

app/views/admin/badges/new.html.slim
h1 New badge

= render 'form'

app/views/admin/badges/show.html.slim
h1 Badges show

table.table.table-striped
  caption style='caption-side:top'
  thead.thead-dark
    tr
      th = "Name"
      th = "Img"
      th = "Rule Type"
      th = "Param"
  tbody
  tr
    td.align-middle = @badge.name
    td.align-middle = image_tag @badge.img
    td.align-middle = @badge.rule_type
    td.align-middle = @badge.param

= link_to t('.back'), admin_badges_path(@badge)

app/views/admin/badges/update.html.slim
h1 Bagdes#update
p Find me in app/views/bagdes/update.html.slim

app/views/badges/index.html.slim
table.table.table-striped
  caption style='caption-side:top' Список возможных Наград
  thead.thead-dark
    tr
      th = "Name"
      th = "Img"
  tbody
    - @badges.each do |badge|
      tr
        td.align-middle = badge.name
        td.align-middle = image_tag badge.img