config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
   controllers: { sessions: 'users/sessions'}

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  get 'contact_us', to: 'contact_us#show'
  post 'contact_us/create', to: 'contact_us#create'
  get 'badges', to: 'badges#index'

  namespace :my do
    get 'badges', to: 'badge_issueds#index'
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :before_save_set_next_question

  def complete!
    self.current_question = nil
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def correct_percent
    (100.to_f/test.questions.count)*correct_questions
  end

  def questions_counter
    test.questions.where('id <= ?', current_question.id).count
  end

  def success?
    correct_percent > 84
  end

  def time_is_up?
    remaining_time < 0 if remaining_time
  end

  def remaining_time
    self.test.timer*60 - (Time.now - self.created_at).ceil if self.test.timer
  end

  private

  def before_save_set_next_question
    self.current_question = next_question
  end

  def next_question
    if current_question.nil?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.pluck(:id).sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test_passage, only: [:show, :update, :result, :gist]

  def show
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])
    
    @test_passage.complete! if @test_passage.time_is_up?

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)

      #to give certain Badges to User if test ended successfully
      give_budges if @test_passage.success?

    else
      render :show
    end
  end

  def gist
    question = @test_passage.current_question
    @result = GistQuestionService.new(question).call

    flash_options =
      if @result.success?
        current_user.gists.create!(url: @result.id, question: question)
        {notice: @result.html_url}
      else
        {alert: t('.failure')}
      end

    redirect_to @test_passage, flash_options
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def give_budges

    service = BadgeService.new(@test_passage)
    badges = service.call

    badges.each do |badge|
      current_user.badge_issueds.create!(badge: badge) if badge.present?
    end
    flash[:notice] = "У вас новые награды! #{badges.count}шт." if badges.any?

  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.slim
h1 = t('.header', title: @test_passage.test.title)
- if @test_passage.success?
  .percent
    div
      = t('.test_failed')
    .win #{@test_passage.correct_percent.to_i}%
- else
  .percent
    div
      = t('.test_passed')
    .lose #{@test_passage.correct_percent.to_i}%
= link_to t('.test_list'), tests_path(@test_passage.test)

app/views/test_passages/show.html.slim
-if @test_passage.test.timer
  .hide
    .time = @test_passage.remaining_time
    = link_to "Result", result_test_passage_path, class:'result-button'
  .timer
    span.timer__minutes
    span.hide-timer__span-colon
      |:
    span.timer__seconds

.progress
  .progress-bar#test_show_progress aria-valuemax="0" aria-valuemin="100" aria-valuenow="0" role="progressbar" style=("width: 4%;")  1%

.row.justify-content-center
  .col.col-md-12
    h1 = t('.passing', title: @test_passage.test.title)

    p
      = t('.question')
      |  #{@test_passage.questions_counter} of #{@test_passage.test.questions.count}

    b = @test_passage.current_question.body

    = form_with url: test_passage_path(@test_passage),
                local: true, method: :put,
                data: { current_number: @test_passage.questions_counter,
                        total_count: @test_passage.test.questions.count } do |form|
      = form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b|
        .form-check
          = b.check_box id: "answer_ids_#{b.object.id}"
          = b.label
      = form.submit t('.next'), class:"next"

p.btn.btn-outline-info.my-2 = link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post
p.btn.btn-outline-danger.my-2 = link_to t('.break_test'), tests_path, class: 'break_test'