config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
   controllers: { sessions: 'users/sessions'}

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  get 'contact_us', to: 'contact_us#show'
  post 'contact_us/create', to: 'contact_us#create'
  get 'badges', to: 'badges#index'

  namespace :my do
    get 'badges', to: 'badge_issueds#index'
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end

end

app/models/admin.rb
class Admin < User

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answers_count, on: :create

  scope :correct, -> { where(correct: true) }


  private

  def answers_count
    message = "Количество ответов не должно превышать 4"
    errors.add(:answer_count, message) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_issueds, dependent: :destroy
  has_many :users, through: :badge_issueds

  validates :name, presence: true, uniqueness: true
  validates :img, presence: true
  validates :rule_type, presence: true
end

app/models/badge_issued.rb
class BadgeIssued < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true, uniqueness: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author , class_name: "User"
  has_many :questions, dependent: :destroy
  has_many :test_passages
  has_many :users, through: :test_passages

  validates :title, presence: true, uniqueness: {scope: :level}
  validates :level, numericality: {
    only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :averages, -> { where(level: 2..4) }
  scope :difficult, -> { where(level: 5..Float::INFINITY) }

  scope :by_category, -> (category_title) {
    joins(:category)
    .where(categories: { title: category_title }).order(title: :desc)
  }

  def self.titles_by_category(category_title)
    by_category(category_title).pluck(:title)
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :before_save_set_next_question

  def complete!
    self.current_question = nil
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def correct_percent
    (100.to_f/test.questions.count)*correct_questions
  end

  def questions_counter
    test.questions.where('id <= ?', current_question.id).count
  end

  def success?
    correct_percent > 84
  end

  def time_is_up?
    remaining_time < 0 if remaining_time
  end

  def remaining_time
    self.test.timer*60 - (Time.now - self.created_at).ceil if self.test.timer
  end

  private

  def before_save_set_next_question
    self.current_question = next_question
  end

  def next_question
    if current_question.nil?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.pluck(:id).sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: "Test", foreign_key: "author_id"
  has_many :gists
  has_many :badge_issueds
  has_many :badges, through: :badge_issueds

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true,
  format: { with: /.+@.+\..+/i }
  validates :password, presence: true
  validates :password, confirmation: true

  def passed_tests(level)
    self.tests.where("level = :level", level: level).distinct
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def admin?
    is_a?(Admin)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def test_params
    params.require(:test).permit(:title, :level, :category_id)
  end

  def find_test
    @test = Test.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def curren_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

end

app/helpers/bagdes_helper.rb
module BagdesHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title TestGuru
    meta [name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
  body.justify-content-sb

    = render 'shared/admin/nav'

    .leftSide

    main.min-height
      .container
        = render 'shared/flash'

        = yield

    .rightSide
    footer.bg-dark
      .container-fluid
        .row
          .col-md-6
            p = t('.app_description')
            .ml-1= link_to "Donate", '#'
      .row.mx-auto.justify-content-center.mt-3
        p.mr-1 ©
        p.mr-1 = curren_year
        p.mr-1 = github_url('GLexx909', 'test_guru')
        p = link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com', target: '_blank'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TestGuru
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title TestGuru
    meta [name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
  body.justify-content-sb

    = render 'shared/nav'

    main.min-height
      .container
        = render 'shared/flash'

        = yield

    footer.bg-dark
      .container-fluid
        .row.d-flex.justify-content-between
          .col-md-4
            p = t('.app_description')
            .ml-1= link_to "Donate", '#'
          .col-md-2
            strong = link_to t('.contact_us'), contact_us_path
      .row.mx-auto.justify-content-center.mt-3
        p.mr-1 ©
        p.mr-1 = curren_year
        p.mr-1 = github_url('GLexx909', 'test_guru')
        p = link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com', target: '_blank'

app/views/shared/_errors.html.slim
- if resourse.present? && resourse.errors.any?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resourse.id }
    div
      h2
        = t('.header', count: resourse.errors.count)
      - resourse.errors.full_messages.each do |message|
        ul
          li = message

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  = content_tag :p, message, class: "flash #{key} alert-#{key}", role: "alert"

app/views/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .navbar-brand = link_to 'TEST GURU', root_path
  #navbarResponsive.collapse.navbar-collapse
    ul.navbar-nav.ml-auto
      - if user_signed_in?
        li.nav-item.align-self-center = t('.welcome_message', name: current_user.name)
        li.nav-item = link_to "Награды", my_badges_path, class: 'nav-link active'
        li.nav-item = link_to t('.signout'),  destroy_user_session_path, method: :delete, class: 'nav-link active'
      - else
        li.nav-item = link_to t('.signup'), new_user_registration_path, class: 'nav-link active'
        li.nav-item = link_to t('.login'), new_user_session_path, class: 'nav-link active'

app/views/shared/admin/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .navbar-brand = link_to 'TEST GURU', admin_tests_path
  #navbarResponsive.collapse.navbar-collapse
    ul.navbar-nav.ml-auto
      - if user_signed_in?
        li.nav-item.align-self-center.text-white = t('layouts.admin.welcome_message', name: current_user.name)
        li.nav-item
          = link_to t('admin.nav.control_panel'), admin_tests_path, class: 'nav-link active'
        li.nav-item
          = link_to t('admin.nav.badges'), admin_badges_path, class: 'nav-link active'
        li.nav-item
          = link_to 'Gists', admin_gists_path, class: 'nav-link active'
        li.nav-item
          = link_to t('admin.tests.index.new_test'), new_admin_test_path, class: 'nav-link active'
        li.nav-item
          = link_to t('layouts.admin.signout'), destroy_user_session_path, method: :delete, class: 'nav-link active'
      - else
        li.nav-item
          = link_to t('layouts.admin.signup'), new_user_registration_path, class: 'nav-link active'
        li.nav-item
          = link_to t('layouts.admin.login'), new_user_session_path, class: 'nav-link active'